[tox]
envlist =
    mypy
    py310
    py311
    py312
    py313
    py314
    pypy3
isolated_build = true
package = wheel

[testenv]
deps =
    -r{toxinidir}/requirements/test.txt
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}
commands =
    pytest -vv

[testenv:coverage]
deps =
    -r{toxinidir}/requirements/test.txt
commands =
    coverage run --source=genericname -m pytest

[testenv:mypy]
deps =
    -r{toxinidir}/requirements/mypy.txt
commands =
    mypy src
